@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 06 14:07:04 +0700 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim tb_wrapped_behav -key {Behavioral:sim_1:Functional:tb_wrapped} -tclbatch tb_wrapped.tcl -view C:/Users/PTNgoc/DA_TKLL_ALU_FIXED_POINT/tb_wrapped_behav.wcfg -log simulate.log"
call xsim  tb_wrapped_behav -key {Behavioral:sim_1:Functional:tb_wrapped} -tclbatch tb_wrapped.tcl -view C:/Users/PTNgoc/DA_TKLL_ALU_FIXED_POINT/tb_wrapped_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
